#### Numpy - make

- array : list와 비슷하다. 하지만 타입이 다르고 np의 배열이 더 빠르다.
- reshape : 형태를 다시만드는 것, 1x8 을 2x4로 바꾸는 등
- index
- zeros
- ones
- eye
- like
- empty : 비어있는 행렬을 만든다.
- arange : range하고 똑같다. 하지만 빠르다.
- linspace, logspace : 데이터가 있을때 linear space기준으로 분할한다.
- random - rand, randn (numpy의 random과 random모듈이 다르게 동작한다.)
- stack, concat: 2개 이상의 array를 합치는 방법, stack concat 합치는 방법 다르다.
- split
- sort
    


### array

- ndim: 행렬의 차원 (1차원 2차원 ...)
- shape : 행렬의 모양을 나타낸다.



In [4]:
import numpy as np

In [5]:
# 1차원 배열

array = np.array([0,1,2,3])
print(type(array),array)

<class 'numpy.ndarray'> [0 1 2 3]


In [7]:
# 2차원 배열

array = np.array([
    [0,1],
    [1,2],
    [2,3],
])
print(array)

[[0 1]
 [1 2]
 [2 3]]


In [8]:
# 3차원 배열

array = np.array([
    [[0,1,2,3],
    [4,5,6,7],
    [8,9,10,11]],
    
    [[0,1,2,3],
    [4,5,6,7],
    [8,9,10,11]],
])
print(array)

print(array.ndim, array.shape)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]]
3 (2, 3, 4)


In [ ]:
# 안쪽에서 바깥쪽에서의 갯수라고 생각하면 편하게 생각할 수 있다.

#### reshape

- 행렬의 모양을 바꿀 수 있다.


In [10]:
na = np.array(range(1,9))
na

array([1, 2, 3, 4, 5, 6, 7, 8])

In [11]:
# 첫번째 방법

na.reshape(2,4) # 행렬의 모양을 바꿔줄 수 있다.

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [13]:
# 두번째 방법

np.reshape(na, (4,2))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [14]:
rna = np.reshape(na, (4,2))
rna

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [16]:
rna.T, rna.T.shape

(array([[1, 3, 5, 7],
        [2, 4, 6, 8]]), (2, 4))

#### index

- 행렬의 특정 위치 값을 가져오기
- 행렬 자르기

In [17]:
# 리스트 처럼 똑같이 슬라이싱 가능하다.

array

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [20]:
# 슬라이싱 방법 두가지
print(array[1][1][2])

6


In [21]:
print(array[1, 1, 2])

6


In [24]:
# 행렬 자르기
result = array[1:,1:,2:]

In [25]:
result

array([[[ 6,  7],
        [10, 11]]])

In [26]:
array[0]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [29]:
# 차원이 하나씩 줄어든다.
array.ndim, array[0].ndim, array[0][1].ndim

(3, 2, 1)

In [30]:
# 데이터 수정

data = np.array(range(5))
data

array([0, 1, 2, 3, 4])

In [31]:
data[2]

2

In [32]:
# 특정 위치에 대입 해주면 된다.
data[2] = 0

In [33]:
data

array([0, 1, 0, 3, 4])

In [34]:
data[3:] = 2

In [35]:
data

array([0, 1, 0, 2, 2])

In [36]:
# 한꺼번에 바꾸는 거 broad casting 이라고 한다.

In [38]:
# 2차원 행렬 데이터 바꾸기

data = np.array([range(3), range(3,6)])
data


array([[0, 1, 2],
       [3, 4, 5]])

In [39]:
data[1:, 1:] = 10
data

array([[ 0,  1,  2],
       [ 3, 10, 10]])

#### zeros

- 행렬을 만들고 안에 0으로 채워 넣습니다.

In [40]:
z = np.zeros(5) # 기본적으로 float으로 생성 되는데

In [41]:
z

array([0., 0., 0., 0., 0.])

In [42]:
z = np.zeros(5, dtype = int) # 기본적으로 float으로 생성 되는데 int로 바꾸고 싶으면 뒤에 옵션 적어주면된다.
z

array([0, 0, 0, 0, 0])

In [44]:
z = np.zeros((2,3), dtype=int)
z

array([[0, 0, 0],
       [0, 0, 0]])

In [46]:
z = np.zeros((2,3,4), dtype=int)
z

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

#### ones
- 행렬을 만들고 1로 채운다.


In [49]:
one = np.ones([2,3,4], dtype = int)
one

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

#### eye
- 단위 행렬 데이터를 만듭니다.

In [51]:
np.eye(5, dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

#### like
- 행렬안에 있는 모든 데이터를 0이나 1으로 바꿀 수 있습니다.

In [52]:
z

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [54]:
# 모두 1로 바꿔준다.
np.ones_like(z)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [55]:
np.zeros_like(one)

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

#### empty (거의 쓰는 일 없다.)
- 빈행렬 데이터를 만듭니다.
- 안에 어떤 데이터가 들어갈지 알 수 없다.

In [59]:
np.empty((6, 6)) # shape 적어 주면 된다.

array([[-3.10503618e+231, -3.10503618e+231,  2.23137236e-314,
         4.94065646e-323,  5.43472210e-323,              nan],
       [ 1.57615451e-260,  3.03441780e-294,  1.06559868e-255,
        -1.90087090e-075,  2.25193094e-314,  2.23219937e-314],
       [ 1.88777477e+052,  2.24528421e-314,  2.25044708e-314,
         2.06395567e-048,  2.25193100e-314,  2.25194708e-314],
       [ 4.17742642e+042,  2.24113988e-314,  2.23219945e-314,
        -4.23134774e-164,  2.23389177e-314,  2.23201000e-314],
       [-6.59200205e+038,  2.25257257e-314,  2.23220049e-314,
        -4.49796939e-062,  2.25194714e-314,  2.23261655e-314],
       [ 1.22279446e-306,  2.25194717e-314,  2.23261652e-314,
        -5.44931109e+305,  2.23731479e-314,  2.23292939e-314]])

#### arange
- range 와 사용법은 같다..
- 하지만 큰 데이터를 만들때 속도가 빠르다.

In [83]:
size = int(1E6)
size

1000000

In [84]:
%timeit for x in range(size): x ** 2
%timeit for x in np.arange(size): x ** 2

362 ms ± 6.46 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
235 ms ± 5.99 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [85]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [86]:
np.arange(2, 10, 3)

array([2, 5, 8])

#### linspace, logspace

In [87]:
# 앞, 뒤, 몇개로 나눌 것인지
np.linspace(0, 100, 3)

array([  0.,  50., 100.])

In [88]:
np.linspace(0, 100, 4)

array([  0.        ,  33.33333333,  66.66666667, 100.        ])

In [89]:
np.linspace(0, 100, 5)

array([  0.,  25.,  50.,  75., 100.])

In [90]:
# 10의 2승 3승 4승, log10(x) = 2

np.logspace(2,4,3)

array([  100.,  1000., 10000.])

In [91]:
np.logspace(2,3,3)

array([ 100.        ,  316.22776602, 1000.        ])

#### random
- seed : 랜덤값을 결정해주는 값
- rand : uniform(균등분포)하게 랜덤 값을 뽑아준다. (뽑히는 숫자의 횟수가 균등분포)
- randn : gaussian(정규분포)로 랜덤값을 뽑아줍니다. 많이 쓸 것이다.** (뽑히는 숫자의 횟수가 정규분포)
- randint : 정수를 랜덤하게 뽑아준다.
- shuffle :  섞어주는 함수
- choice : 여러개 중에서 선택해주는 함수

1 ~ 5까지 뽑는다.

1 2 3 4 5

여기서 균등분포는 100개 뽑을때 각각이 20번씩 뽑히는 것을 말하고

정규분포는 0과 가까울 수록 뽑히는 빈도수가 더 높다.

실행할때마다 다른 수가 뽑히게 된다.

seed 값 여러개 대입해서 랜덤값이 어떻게 나오는지 알 수 있고
random값에 seed를 넣어서 동일한 값이 나오도록 만들어서 테스트 한다.  

In [99]:
np.random.seed(0) # 0으로 seed값 설정
rd = np.random.rand(10)
rd

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ,
       0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152])

In [100]:
rd

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ,
       0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152])

In [102]:
rd = np.random.rand(2,5)
rd

array([[0.97861834, 0.79915856, 0.46147936, 0.78052918, 0.11827443],
       [0.63992102, 0.14335329, 0.94466892, 0.52184832, 0.41466194]])

In [107]:
rdn = np.random.randn(2,5)
rdn # 0과 가까운 값들이 많이 나온다. 정규분포로 랜덤 값을 뽑는다.

array([[-0.81314628, -1.7262826 ,  0.17742614, -0.40178094, -1.63019835],
       [ 0.46278226, -0.90729836,  0.0519454 ,  0.72909056,  0.12898291]])

In [111]:
# randint(정수값으로 랜덤 값 뽑게 된다.)

np.random.randint(3)

# 3보다 작은 숫자가 나타난다

2

In [135]:
np.random.randint(3, 10) # 3~ 9 까지의 수

3

In [136]:
np.random.randint(5, 11, (3,3)) # 5~11 사이에 3,3 행렬 만들어진다.

array([[5, 5, 8],
       [5, 7, 7],
       [5, 9, 8]])

In [138]:
np.random.randint(5, (3,3)) # 행렬 사이즈 적었을때 default파라미터 때문에 마지막 수 적어야 한ㄷ.

TypeError: int() argument must be a string, a bytes-like object or a number, not 'tuple'

In [139]:
np.random.randint(5, 11, (3,3)) # 5~11 사이에 3,3 행렬 만들어진다.

array([[ 9, 10,  5],
       [ 9,  8, 10],
       [ 8,  9, 10]])

In [143]:
# shuffle 로 데이터 순서를 바꿀 수 있습니다.

np.random.shuffle(data)
data.shape, data


((2, 3), array([[ 3, 10, 10],
        [ 0,  1,  2]]))

In [145]:
# choice
np.random.choice(5, 10, p=[0.1, 0, 0.3, 0.6, 0])

#  다섯개의 숫자에 확률을 다 맞춰준다.

array([3, 3, 2, 2, 3, 3, 2, 0, 2, 3])

In [146]:
data

array([[ 3, 10, 10],
       [ 0,  1,  2]])

In [148]:
# unique
index, count = np.unique(data, return_counts = True)

# return 을 튜플로 한다.
print(index)
print(count)

# 각 숫자들과 몇번 나왔는지 카운트를 해준다.

[ 0  1  2  3 10]
[1 1 1 1 2]


#### stack
- 행렬을 쌓는 것처럼 합치는 방법

In [149]:
na1 = np.arange(6)
print(na1)

[0 1 2 3 4 5]


In [152]:
na2 = np.arange(6,12)
print(na2)

[ 6  7  8  9 10 11]


In [157]:
# axis가 0이면 가로로 쌓는다.
na3 = np.stack((na1, na2))
print(na3, na3.shape)

# 쌓이게 된다.


[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]] (2, 6)


In [158]:
# axis 가 1일때 세로로 쌓게 된다.

na3 = np.stack((na1, na2), axis = 1)
print(na3, na3.shape)


# axis가 차원을 나타내는 형태로 사용된다. 차원을 한차원씩 안으로 들어가서 바꿔가면서 stack 하는 기본을 바꿔줄 수 있다.
# 0 : 가장 큰 차원, 1: 그다음 큰 차원, 2: 그다음 큰차원
# 쌓이게 된다.

[[ 0  6]
 [ 1  7]
 [ 2  8]
 [ 3  9]
 [ 4 10]
 [ 5 11]] (6, 2)


In [159]:
na1 = np.random.randint(10, size=(2,3))
print(na1)
na2 = np.random.randint(10, size=(2,3))
print(na2)

[[6 8 8]
 [3 2 3]]
[[6 3 6]
 [5 7 0]]


In [160]:
na4 = np.stack((na1, na2), axis = 1)
print(na4, na4.shape)

[[[6 8 8]
  [6 3 6]]

 [[3 2 3]
  [5 7 0]]] (2, 2, 3)


In [161]:
# vstack 수직으로

# [0,1,2] [1,2,3] [2,3,4] [3,4,5] [4,5,6]

ls = []

for idx in range(5):
    ls.append(range(7)[idx:idx+3])
ls

[range(0, 3), range(1, 4), range(2, 5), range(3, 6), range(4, 7)]

In [162]:
np.vstack(ls)

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [163]:
np.hstack(ls)

array([0, 1, 2, 1, 2, 3, 2, 3, 4, 3, 4, 5, 4, 5, 6])

In [164]:
# 나누는 것 list comprehension 으로 할 수 있다.
ls = [list(range(7)[idx:idx+3]) for idx in range(5)]

In [165]:
ls

[[0, 1, 2], [1, 2, 3], [2, 3, 4], [3, 4, 5], [4, 5, 6]]

In [167]:
# 0~4까지의 숫자가 처음부터 끝까지 new line이 되도록 만들 수 있다.
np.arange(5)[:, np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4]])

#### concatenate 결합

- 가로결합 : 행의 갯수가 같아야 합니다.
- 세로결합 : 열의 갯수가 같아야 합니다.

In [168]:
r1 = np.random.randint(10, size=(2,3))
r1

array([[8, 4, 6],
       [5, 8, 2]])

In [169]:
r2 = np.random.randint(10, size=(3,2))
r2

array([[3, 9],
       [7, 5],
       [3, 4]])

In [170]:
r3 = np.random.randint(10, size=(3, 3))
r3

array([[5, 3, 3],
       [7, 9, 9],
       [9, 7, 3]])

In [171]:
np.concatenate((r1, r3)) # axis = 0 default값

array([[8, 4, 6],
       [5, 8, 2],
       [5, 3, 3],
       [7, 9, 9],
       [9, 7, 3]])

In [174]:
np.concatenate((r1, r3), axis=1)  # axis = 0 default값

ValueError: all the input array dimensions except for the concatenation axis must match exactly

#### split

In [177]:
r = np.arange(10,20)
r

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [179]:
r1 = np.split(r, [5])  #r을 인덱스 5개 단위로
r1

[array([10, 11, 12, 13, 14]), array([15, 16, 17, 18, 19])]

In [180]:
r2 = np.split(r, [2,4,6,8])
r2

[array([10, 11]),
 array([12, 13]),
 array([14, 15]),
 array([16, 17]),
 array([18, 19])]

In [181]:
# vsplit - 행렬을 수평으로 나눈다. 칼로 자른 것 처럼

r = np.random.randint(10, size=(4,6))
r

array([[2, 3, 9, 7, 7, 5],
       [1, 2, 2, 8, 1, 5],
       [8, 4, 0, 2, 5, 5],
       [0, 8, 1, 1, 0, 3]])

In [182]:
np.vsplit(r, [2])

[array([[2, 3, 9, 7, 7, 5],
        [1, 2, 2, 8, 1, 5]]), array([[8, 4, 0, 2, 5, 5],
        [0, 8, 1, 1, 0, 3]])]

In [185]:
r1 = np.vsplit(r, [2,3])
r1

[array([[2, 3, 9, 7, 7, 5],
        [1, 2, 2, 8, 1, 5]]),
 array([[8, 4, 0, 2, 5, 5]]),
 array([[0, 8, 1, 1, 0, 3]])]

In [186]:
# hsplit - 행렬을 수직으로 나눠줍니다.

In [189]:
r1, r2 = np.hsplit(r, [2])
print(r1)
print(r2)

[[2 3]
 [1 2]
 [8 4]
 [0 8]]
[[9 7 7 5]
 [2 8 1 5]
 [0 2 5 5]
 [1 1 0 3]]


#### sort

In [210]:
r1 = np.random.randint(10, size = (3,3))
r1

array([[3, 3, 8],
       [8, 7, 0],
       [3, 8, 7]])

In [211]:
r1.sort()
r1
# 행렬 안에서만 세로로 sorting 된다.

array([[3, 3, 8],
       [0, 7, 8],
       [3, 7, 8]])

In [212]:
r1.sort(axis=0)
r1
# 가로로 sorting이 된다.

array([[0, 3, 8],
       [3, 7, 8],
       [3, 7, 8]])

In [213]:
np.c_[np.array([1,2,3]), np.array([4,5,6])]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [214]:
np.r_[np.array([1,2,3]), np.array([4,5,6])]

array([1, 2, 3, 4, 5, 6])