#### Numpy - Calculate

- 기본연산 : 

In [5]:
# 기본연산
import numpy as np

ls = [1,2,3]
ls*3

# 리스트는 요소를 반복해주는 뜻

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [6]:
ls = [num*3 for num in ls]
ls

[3, 6, 9]

In [8]:
na = np.array([1,2,3])
na

# 각 요소에 연산이 되어서 변경되는 것

array([1, 2, 3])

In [10]:
na*3

array([3, 6, 9])

In [12]:
na1 = np.array([1,2,3])
na2 = np.array([4,5,6])
na1 * na2

# 배열끼리 곱셈이 가능하다.

array([ 4, 10, 18])

In [16]:
# 비교연산 : 각각의 요소를 매칭해서 T/F를 호출해준다.

na1 == 2, na2 > 5

(array([False,  True, False]), array([False, False,  True]))

In [17]:
na1 = np.array(range(10))
na1


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
print(na1)
na1 %3 == 0

# True/False가지고 필터링을 할 수 있다.
is3 = na1 % 3 == 0
is3


[0 1 2 3 4 5 6 7 8 9]


array([ True, False, False,  True, False, False,  True, False, False,
        True])

In [25]:
na1[is3]

array([0, 3, 6, 9])

In [27]:
na1[na1 % 2 == 0] # 이거 잘 알고 있어야 한다 많이 사용됨!!!!!!!!!!

array([0, 2, 4, 6, 8])

#### 브로드 캐스팅

In [31]:
na1 = np.arange(12)
na2 = na1.reshape(3,4)
na3 = np.ones((3,4), dtype=int)
print(na1)
print(na2)
print(na3)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [32]:
na2 + na3

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [33]:
na2 + 1 # 행렬에 덧셈을 하면 모든 element에 +1이 자동으로 되는데 이를 broad casting이라고한다.

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [42]:
# row, column에 대한  브로드 캐스팅
na4 = np.arange(4)
print(na4, na4.shape)

[0 1 2 3] (4,)


In [36]:
na2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [38]:
na2 + na4 # 각각의 행에 더해졌다.

array([[ 0,  2,  4,  6],
       [ 4,  6,  8, 10],
       [ 8, 10, 12, 14]])

In [43]:
# column 열에 더해지는 것

In [46]:
na5 = np.arange(3)[:, np.newaxis]  # np.newaxis
na5, na5.shape

(array([[0],
        [1],
        [2]]), (3, 1))

In [47]:
na2 + na5

array([[ 0,  1,  2,  3],
       [ 5,  6,  7,  8],
       [10, 11, 12, 13]])

#### functioins
- min, max, argmin, argmax
- sum, mean, median, std, var
- all, any
- quartile : 쿼터 나누는 것
- exp, log

In [51]:
r = np.random.randint(10, size=(2,3))
r 

array([[6, 0, 5],
       [5, 2, 9]])

In [52]:
r.min()

0

In [53]:
r.max()

9

In [54]:
r.argmin() #최소값의 위치를 알려준다.

1

In [56]:
r.argmax() # 최댓값의 위치를 알려준다.

5

In [58]:
r.mean()

4.5

In [59]:
np.sum(r)

27

In [60]:
np.sum(r)/6

4.5

In [61]:
np.sum(r, axis=0)

array([11,  2, 14])

In [62]:
np.sum(r, axis=1)

array([11, 16])

In [63]:
# 중간값
r

array([[6, 0, 5],
       [5, 2, 9]])

In [64]:
np.median(r)

5.0

In [66]:
# 표준편차

np.std(r)

2.8722813232690143

In [67]:
np.var(r)

8.25

In [68]:
# all - 모든 조건이 충족하면 True 

In [69]:
# any - all의 반대, 하나의 조건만 충족하면 True

# all과 any, and or 개념과 비슷하다고 생각하면 된다.

# 왜사용?


In [70]:
n1 = np.array(range(3,8))
n1

array([3, 4, 5, 6, 7])

In [71]:
n2 = n1

In [72]:
n2

array([3, 4, 5, 6, 7])

In [73]:
n3 = np.array([3, 4, 0, 6, 7])
n3

array([3, 4, 0, 6, 7])

In [74]:
n1 == n2, n1 == n3

(array([ True,  True,  True,  True,  True]),
 array([ True,  True, False,  True,  True]))

In [75]:
np.all(n1 == n2), np.all(n1 == n3) # 모든 조건이 True일때 True
np.any(n1 == n2), np.any(n1 == n3)

(True, True)

In [77]:
# any
n4 = np.array(range(10,15))
print(n4)
n4 == n1

[10 11 12 13 14]


array([False, False, False, False, False])

In [82]:
# 사분위수
# split통해서 나눈 것처럼 이거는 4개로 나누게 된다.

na = np.arange(100,201)
print(na)

[100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153
 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171
 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188 189
 190 191 192 193 194 195 196 197 198 199 200]


In [83]:
np.percentile(na, 25), np.percentile(na, 62),

# 25%, 62%에 해당하는 데이터가 나오게 된다.


(125.0, 162.0)

In [84]:
# 지수함수
na = np.arange(1,6)
na

array([1, 2, 3, 4, 5])

In [86]:
np.exp(na) # 각 숫자에 해당하는 지수함수가 나오게 된다.

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

In [87]:
na = np.arange(1,6)
na

array([1, 2, 3, 4, 5])

In [88]:
np.log(na)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [89]:
# 함수에 따라서 log,지수함수 취하는 경우 달라지는데
# 수치가 너무 작을 때 지수함수를 넣어서 수치를 뻥튀기 해준다. 비교하기 편해진다.
# 로그함수는 그 반대로 수치 데이터가 너무 커서 스케일 줄어들게 하고 싶을 때 사용하면 된다.

In [90]:
# 파이썬 vs numpy 퍼포먼스 비교를 해보자

#### 성능확인

In [91]:
# 10**7개의 리스트에서 3과 5의 배수의 갯수를 찾는시간

In [97]:
%%time
ls= []
size = int(10E7)
for data in range(size):
    ls.append(data)
len(ls)

CPU times: user 17.8 s, sys: 4.39 s, total: 22.2 s
Wall time: 22.6 s


In [99]:
%%time
la = np.arange(size)
len(la)

CPU times: user 271 ms, sys: 523 ms, total: 794 ms
Wall time: 895 ms


In [101]:
%%time
count = 0
for idx in range(len(ls)):
    if (ls[idx] % 3 == 0) or (ls[idx] % 3 == 0):
        count += 1
print(count)

33333334
CPU times: user 28.3 s, sys: 2.85 s, total: 31.1 s
Wall time: 31.7 s


In [104]:
%%time
count = len(la[(la%3 ==0) | (la%5 == 0)])
count

# list comprehension 사용하면 더 빠르게 될 것이다.

CPU times: user 4.16 s, sys: 952 ms, total: 5.12 s
Wall time: 5.17 s


In [ ]:
class Function 